version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - "server"

  server:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "80:80"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - "db"

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USERNAME}
      MARIADB_PASSWORD: $DATABASE_PASSWORD

      
