version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "80:80"
    environment:
      DB_HOST: db:3306
